import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */
export const products = [
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/wfwetz",
    alt: "product image of sweatshirt",
    productTitle: "Mist",
    color: "black",
    productDesc: "Navy Blue Plus Size Zipper Sweatshirts",
    productPrice: 899,
    productOgPrice: 1000,
    starRating: 5,
    lazyLoading: "loading='lazy'",
    brands: "mist",
    color: 'black'
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/ahvkiq",
    alt: "product image of hoodie",
    productTitle: "chucks",
    productDesc: "Feel Good Lilac Solid Hoodie",
    productPrice: 799,
    color: "white",
    productOgPrice: 900,
    starRating: 1,
    lazyLoading: "loading='lazy'",
    brands: "chucks",
    color: "red",
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/2chnmg",
    alt: "product image of hoodie",
    productTitle: "HRX",
    productDesc: "Red Plum sweatshirt Hoodie",
    productPrice: 999,
    productOgPrice: 1100,
    starRating: 3,
    color: "red",
    lazyLoading: "loading='lazy'",
    brands: "hrx",

  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/bmmzor",
    alt: "product image of full sleeve t-shirt",
    productTitle: "HRX",
    productDesc: "Colorfull style t-shirt",
    productPrice: 599,
    productOgPrice: 700,
    starRating: 2,
    lazyLoading: "loading='lazy'",
    brands: "hrx",
    color: "green",
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/c9ffww",
    alt: "product image of T-shirt Hoodie",
    productTitle: "UCB",
    productDesc: " Feel Good Lilac Henley Hoodie T-shirt",
    productPrice: 759,
    productOgPrice: 900,
    starRating: 1,
    color: "green",
    lazyLoading: "loading='lazy'",
    brands: "ucb",
    color: "green"

  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/v17yda",
    alt: "product image of joggers",
    productTitle: "HRX",
    productDesc: "UpBeat Blue style joggers",
    productPrice: 999,
    productOgPrice: 1150,
    starRating: 3,
    color: "red",
    lazyLoading: "loading='lazy'",
    brands: "hrx",
    color: "blue"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/6xpcev",
    alt: "product image of sweatshirt",
    productTitle: "Metro",
    productDesc: "Sport shoes with style",
    productPrice: 1099,
    productOgPrice: 1500,
    starRating: 5,
    color: "white",
    lazyLoading: "loading='lazy'",
    brands: "metro",
    color: "blue"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/1dyvmk",
    alt: "product image of ucb T-shirt",
    productTitle: "UCB",
    productDesc: "Polo T-Shirt with Tipping",
    productPrice: 699,
    productOgPrice: 750,
    starRating: 2,
    lazyLoading: "loading='lazy'",
    brands: "metro",
    color: "black"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/tubgi1",
    alt: "product image of t-shirt",
    productTitle: "Highlander",
    productDesc: "Slim Fit Casual Shirt",
    productPrice: 599,
    productOgPrice: 700,
    starRating: 2,
    lazyLoading: "loading='lazy'",
    brands: "harbour",
    color: "red"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/8ed5ur",
    alt: "product image of t-shirt",
    productTitle: "Lee Cooper",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 799,
    productOgPrice: 900,
    starRating: 1,
    lazyLoading: "loading='lazy'",
    brands: "harbour",
    color: "green"
  },
  {
    _id: uuid(),
    imgUrl: 'https://rb.gy/bmmzor',
    alt: "product image of t-shirt",
    productTitle: " Cooper",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 299,
    productOgPrice: 900,
    starRating: 1,
    lazyLoading: "loading='lazy'",
    brands: "ucb",
    color: "blue"
  },
  {
    _id: uuid(),
    imgUrl: 'https://rb.gy/c9ffww',
    alt: "product image of t-shirt",
    productTitle: "Lee",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 499,
    productOgPrice: 900,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "ucb",
    color: "black"
  },

  {
    _id: uuid(),
    imgUrl: 'https://rb.gy/v17yda',
    alt: "product image of t-shirt",
    productTitle: "UCB",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 2399,
    productOgPrice: 900,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "ucb",
    color: "green"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/1dyvmk",
    alt: "product image of t-shirt",
    productTitle: "Harbour",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 599,
    productOgPrice: 900,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "harbour",
    color: "red"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/tubgi1",
    alt: "product image of shirt",
    productTitle: "Mist",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 599,
    productOgPrice: 900,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "mist",
    color: "black"
  },
  {
    _id: uuid(),
    imgUrl: "https://rb.gy/yc3qp6",
    alt: "product image of shirt",
    productTitle: "Mist",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 599,
    productOgPrice: 900,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "mist",
    color: "green"
  }, {
    _id: uuid(),
    imgUrl: "https://rb.gy/cnwbr3",
    alt: "product image of jeans",
    productTitle: "Chucks",
    productDesc: "Brand and Comfort Full Jeans",
    productPrice: 699,
    productOgPrice: 700,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "chucks",
    color: "blue"
  }, {
    _id: uuid(),
    imgUrl: "https://rb.gy/vjuewv",
    alt: "product image of t-shirt",
    productTitle: "Chucks",
    productDesc: "Brand and Comfort Full Sleeve",
    productPrice: 599,
    productOgPrice: 900,
    starRating: 2,
    lazyLoading: "loading='lazy'",
    brands: "chucks",
    color: "blue"
  }, {
    _id: uuid(),
    imgUrl: "https://rb.gy/jh78z7",
    alt: "product image of t-shirt",
    productTitle: "Metro",
    productDesc: "Men Chunky Sneakers",
    productPrice: 599,
    productOgPrice: 900,
    starRating: 4,
    lazyLoading: "loading='lazy'",
    brands: "metro",
    color: "red"
  }, {
    _id: uuid(),
    imgUrl: "https://rb.gy/lmyrix",
    alt: "product image of shorts",
    productTitle: "Metro",
    productDesc: "Men Solid Slim Fit Shorts",
    productPrice: 599,
    productOgPrice: 899,
    starRating: 3,
    lazyLoading: "loading='lazy'",
    brands: "metro",
    color: "black"
  },
];
